# Generated by Django 6.0.7 on 2026-07-12 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tournament_tournamentmatch_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='chain_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
